export const CITY = "CITY";
export const COUNTRY = "COUNTRY";
export const GEODATA = "GEODATA";
export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";
export const ERR_MESSAGE = "ERR_MESSAGE";
export const CHECKBOX_SERVER_WEATHERBIT = "CHECKBOX_SERVER_WEATHERBIT";
export const PUT_WEATHER_SERVER_WEATHERBIT = "PUT_WEATHER_SERVER_WEATHERBIT";
export const LOAD_WEATHER_SERVER_WEATHERBIT = "LOAD_WEATHER_SERVER_WEATHERBIT";
export const CHECKBOX_SERVER_OPENWEATHERMAP = "CHECKBOX_SERVER_OPENWEATHERMAP";
export const PUT_WEATHER_SERVER_OPENWEATHERMAP =
  "PUT_WEATHER_SERVER_OPENWEATHERMAP";
export const ERR_MESSAGE_SERVER_OPENWEATHERMAP =
  "ERR_MESSAGE_SERVER_OPENWEATHERMAP";
